/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_usvm_interpreter_CPythonAdapter */

#ifndef _Included_org_usvm_interpreter_CPythonAdapter
#define _Included_org_usvm_interpreter_CPythonAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_usvm_interpreter_CPythonAdapter
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Lorg/usvm/language/Symbol;)V
 */
JNIEXPORT void JNICALL Java_org_usvm_interpreter_CPythonAdapter_run
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
