comments:
  UndocumentedPublicClass:
    active: true
    searchInNestedClass: false
    excludes:
      - '**/test/**'

complexity:
  ComplexCondition:
    active: true
    threshold: 4

style:
  BracesOnWhenStatements:
    active: false
  CascadingCallWrapping:
    active: true

usvm:
  active: true
  MultilineWhenBranchBraces:
    active: true
  NestedCallArguments:
    active: true
    excludes: [ '**/test/**' ]
