import assert from "node:assert/strict";
import test from "node:test";
import { summarizeCampaign } from "../src/campaign.mjs";

test("campaign aggregates replay-confirmed coverage across projects", () => {
  const report = summarizeCampaign({ cases: [
    campaignCase("a", "p1", 4, 4, 4),
    campaignCase("b", "p2", 2, 2, 1),
  ], marginPoints: 20 });
  assert.equal(report.totals.projects, 2);
  assert.equal(report.totals.totalBranches, 6);
  assert.equal(report.totals.exposeCovered, 6);
  assert.equal(report.totals.usvmCovered, 5);
  assert.equal(report.nonInferiority.passed, true);
});

test("campaign rejects reports produced from different EtsIR branch totals", () => {
  const value = campaignCase("a", "p", 4, 4, 4);
  value.usvm.methods[0].totalBranches = 5;
  assert.throws(() => summarizeCampaign({ cases: [value] }), /branch-total mismatch/);
});

test("campaign rejects coverage generated by internal PBT during external replay", () => {
  const value = campaignCase("a", "p", 4, 4, 4);
  value.externalReplay.methods[0].pbt.generatedExecutions = 1;
  assert.throws(() => summarizeCampaign({ cases: [value] }), /generatedExecutions=0/);
});

function campaignCase(label, project, branches, exposeCovered, usvmCovered) {
  const method = (coveredBranches) => ({
    methods: [{ method: `%dflt::${label}(x: number): number`, totalBranches: branches, coveredBranches,
      totalWallMs: 10, symbolic: { targets: [] } }],
  });
  const externalReplay = method(exposeCovered);
  externalReplay.methods[0].pbt = { generatedExecutions: 0, externalExecuted: 1 };
  return {
    label, project,
    externalReplay,
    usvm: method(usvmCovered),
    exposeRaw: { start: 0, end: 5, done: [] },
  };
}
