package org.usvm.ts.pbt

/** Stable identifiers for diagnostics created on the Kotlin side of the PBT boundary. */
internal object PbtDiagnosticCode {
    const val COVERAGE_REPORT_INVALID = "coverage.report.invalid"
    const val COVERAGE_REPORT_MISSING = "coverage.report.missing"
    const val COVERAGE_SOURCE_MAP_INVALID = "coverage.source-map.invalid"
    const val COVERAGE_SOURCE_MAP_MISSING = "coverage.source-map.missing"

    const val MAPPING_BRANCH_AMBIGUOUS = "mapping.branch.ambiguous"
    const val MAPPING_BRANCH_CFG_UNSUPPORTED = "mapping.branch.cfg.unsupported"
    const val MAPPING_BRANCH_SHAPE_UNSUPPORTED = "mapping.branch.shape.unsupported"
    const val MAPPING_BRANCH_UNMAPPED = "mapping.branch.unmapped"
    const val MAPPING_COVERAGE_PROPERTY_ID_MISMATCH = "mapping.coverage.property-id.mismatch"
    const val MAPPING_COVERAGE_UNAVAILABLE = "mapping.coverage.unavailable"
    const val MAPPING_ENTRY_POINT_AMBIGUOUS = "mapping.entry-point.ambiguous"
    const val MAPPING_ENTRY_POINT_BINDINGS_UNSUPPORTED = "mapping.entry-point.bindings.unsupported"
    const val MAPPING_ENTRY_POINT_UNMAPPED = "mapping.entry-point.unmapped"
    const val MAPPING_SOURCE_LOCATION_UNSUPPORTED = "mapping.source.location.unsupported"
    const val MAPPING_SOURCE_ORIGINS_UNSUPPORTED = "mapping.source-origins.unsupported"
    const val MAPPING_SOURCE_ROOT_UNSUPPORTED = "mapping.source-root.unsupported"
    const val MAPPING_SOURCE_UNAVAILABLE = "mapping.source.unavailable"
    const val MAPPING_STATEMENT_AMBIGUOUS = "mapping.statement.ambiguous"
    const val MAPPING_STATEMENT_UNMAPPED = "mapping.statement.unmapped"

    const val PROPERTY_ID_INVALID = "property.id.invalid"
    const val PROPERTY_INPUTS_EMPTY = "property.inputs.empty"
    const val INPUT_NAME_DUPLICATE = "input.name.duplicate"
    const val INPUT_NAME_INVALID = "input.name.invalid"
    const val DOMAIN_ARRAY_LENGTH = "domain.array.length"
    const val DOMAIN_CONSTANT_UNSUPPORTED = "domain.constant.unsupported"
    const val DOMAIN_INTEGER_BOUNDS = "domain.integer.bounds"
    const val DOMAIN_NUMBER_BOUND_NAN = "domain.number.bound.nan"
    const val DOMAIN_NUMBER_BOUNDS = "domain.number.bounds"
    const val DOMAIN_NUMBER_NAN_BOUNDED = "domain.number.nan-bounded"
    const val DOMAIN_OPTIONAL_NIL = "domain.optional.nil"
    const val DOMAIN_STRING_LENGTH = "domain.string.length"
    const val DOMAIN_TUPLE_EMPTY = "domain.tuple.empty"
    const val ENTRY_POINT_EXPORT_INVALID = "entrypoint.export.invalid"
    const val ENTRY_POINT_MODULE_INVALID = "entrypoint.module.invalid"
    const val JS_NUMBER_ENCODING_INVALID = "js-number.encoding.invalid"
}
