package org.usvm.ts.pbt

/** Stable identifiers for diagnostics created on the Kotlin side of the PBT boundary. */
internal object PbtDiagnosticCode {
    const val CLI_ARGUMENT_INVALID = "cli.argument.invalid"
    const val CLI_COVERAGE_REQUIRED = "cli.coverage.required"
    const val CLI_COVERAGE_SCOPE_INVALID = "cli.coverage.scope.invalid"
    const val CLI_EXAMPLES_INVALID = "cli.examples.invalid"
    const val CLI_NUM_RUNS_INVALID = "cli.num-runs.invalid"
    const val CLI_PROPERTY_EMPTY = "cli.property.empty"
    const val CLI_PROPERTY_INVALID = "cli.property.invalid"
    const val CLI_PROPERTY_UNKNOWN = "cli.property.unknown"
    const val CLI_REGISTRY_EMPTY = "cli.registry.empty"
    const val CLI_REGISTRY_ID_DUPLICATE = "cli.registry.id.duplicate"
    const val CLI_REGISTRY_ID_INVALID = "cli.registry.id.invalid"
    const val CLI_REGISTRY_UNKNOWN = "cli.registry.unknown"
    const val CLI_SINGLE_PROPERTY_REQUIRED = "cli.single-property.required"
    const val CLI_SOURCE_ROOT_REQUIRED = "cli.source-root.required"
    const val CLI_TIMEOUT_INVALID = "cli.timeout.invalid"

    const val REGISTRY_PROPERTY_ID_DUPLICATE = "registry.property-id.duplicate"
    const val REGISTRY_PROPERTY_INVALID = "registry.property.invalid"
    const val REGISTRY_PROVIDER_LOAD_FAILED = "registry.provider.load.failed"

    const val BACKEND_EXAMPLES_ARITY = "backend.examples.arity"
    const val BACKEND_EXAMPLES_DOMAIN = "backend.examples.domain"
    const val BACKEND_EXAMPLES_VALUE_INVALID = "backend.examples.value.invalid"
    const val BACKEND_PROCESS_FAILED = "backend.process.failed"
    const val BACKEND_PROCESS_INTERRUPTED = "backend.process.interrupted"
    const val BACKEND_PROCESS_READ_FAILED = "backend.process.read.failed"
    const val BACKEND_PROCESS_START_FAILED = "backend.process.start.failed"
    const val BACKEND_PROCESS_TIMEOUT = "backend.process.timeout"
    const val BACKEND_PROCESS_WRITE_FAILED = "backend.process.write.failed"
    const val BACKEND_REQUEST_TOO_LARGE = "backend.request.too-large"
    const val BACKEND_RESPONSE_EMPTY = "backend.response.empty"
    const val BACKEND_RESPONSE_INVALID = "backend.response.invalid"
    const val BACKEND_RESPONSE_TOO_LARGE = "backend.response.too-large"
    const val BACKEND_RUNTIME_NOT_FOUND = "backend.runtime.not-found"

    const val COVERAGE_COLLECTOR_NOT_FOUND = "coverage.collector.not-found"
    const val COVERAGE_REPORT_INVALID = "coverage.report.invalid"
    const val COVERAGE_REPORT_MISSING = "coverage.report.missing"
    const val COVERAGE_RUNTIME_UNSUPPORTED = "coverage.runtime.unsupported"
    const val COVERAGE_RUNTIME_VERSION_UNAVAILABLE = "coverage.runtime.version-unavailable"
    const val COVERAGE_SOURCE_MAP_INVALID = "coverage.source-map.invalid"
    const val COVERAGE_SOURCE_MAP_MISSING = "coverage.source-map.missing"

    const val MAPPING_BRANCH_AMBIGUOUS = "mapping.branch.ambiguous"
    const val MAPPING_BRANCH_CFG_UNSUPPORTED = "mapping.branch.cfg.unsupported"
    const val MAPPING_BRANCH_SHAPE_UNSUPPORTED = "mapping.branch.shape.unsupported"
    const val MAPPING_BRANCH_UNMAPPED = "mapping.branch.unmapped"
    const val MAPPING_COVERAGE_PROPERTY_ID_MISMATCH = "mapping.coverage.property-id.mismatch"
    const val MAPPING_COVERAGE_UNAVAILABLE = "mapping.coverage.unavailable"
    const val MAPPING_ENTRY_POINT_AMBIGUOUS = "mapping.entry-point.ambiguous"
    const val MAPPING_ENTRY_POINT_BINDINGS_UNSUPPORTED = "mapping.entry-point.bindings.unsupported"
    const val MAPPING_ENTRY_POINT_UNMAPPED = "mapping.entry-point.unmapped"
    const val MAPPING_SOURCE_LOCATION_UNSUPPORTED = "mapping.source.location.unsupported"
    const val MAPPING_SOURCE_ORIGINS_UNSUPPORTED = "mapping.source-origins.unsupported"
    const val MAPPING_SOURCE_ROOT_UNSUPPORTED = "mapping.source-root.unsupported"
    const val MAPPING_SOURCE_UNAVAILABLE = "mapping.source.unavailable"
    const val MAPPING_STATEMENT_AMBIGUOUS = "mapping.statement.ambiguous"
    const val MAPPING_STATEMENT_UNMAPPED = "mapping.statement.unmapped"

    const val PROTOCOL_REQUEST_INVALID = "protocol.request.invalid"
    const val SOURCE_ROOT_INVALID = "source-root.invalid"

    const val PROPERTY_ID_INVALID = "property.id.invalid"
    const val PROPERTY_INPUTS_EMPTY = "property.inputs.empty"
    const val INPUT_NAME_DUPLICATE = "input.name.duplicate"
    const val INPUT_NAME_INVALID = "input.name.invalid"
    const val DOMAIN_ARRAY_LENGTH = "domain.array.length"
    const val DOMAIN_CONSTANT_UNSUPPORTED = "domain.constant.unsupported"
    const val DOMAIN_INTEGER_BOUNDS = "domain.integer.bounds"
    const val DOMAIN_NUMBER_BOUND_NAN = "domain.number.bound.nan"
    const val DOMAIN_NUMBER_BOUNDS = "domain.number.bounds"
    const val DOMAIN_NUMBER_NAN_BOUNDED = "domain.number.nan-bounded"
    const val DOMAIN_OPTIONAL_NIL = "domain.optional.nil"
    const val DOMAIN_STRING_LENGTH = "domain.string.length"
    const val DOMAIN_TUPLE_EMPTY = "domain.tuple.empty"
    const val ENTRY_POINT_EXPORT_INVALID = "entrypoint.export.invalid"
    const val ENTRY_POINT_MODULE_INVALID = "entrypoint.module.invalid"
    const val JS_NUMBER_ENCODING_INVALID = "js-number.encoding.invalid"
}
