name: Build and Run Tests [gradle]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [ '11' ]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install CPython optional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq\
            libssl-dev \
            libffi-dev

      - name: Build and run tests
        run: |
          ./gradlew build --no-daemon -PcpythonActivated=true

      - name: Run Detekt
        run: |
          ./gradlew detektMain detektTest --no-daemon

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
