# This is a basic workflow to help you get started with Actions

name: Build and Run Tests [gradle]

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
#        java: [ '11', '17' ]
        java: [ '11' ]

    runs-on: [self-hosted, usvm] 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Runs a set of commands using the runners shell
      - name: Build and run tests
        run: ./gradlew build --no-daemon

      - name: Upload usvm test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: usvm-tests-report-linux
          path: ./**/build/reports/tests/test/
