# This is a basic workflow to help you get started with Actions

name: Build and Run Tests [gradle]

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
#        java: [ '11', '17' ]
        java: [ '11' ]

    runs-on: [self-hosted, usvm] 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      # Runs a single command using the runners shell
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install CPython optional dependencies
        run: sudo apt install -y build-essential gdb lcov pkg-config \
              libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
              libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
              lzma lzma-dev tk-dev uuid-dev zlib1g-dev

      # Runs a set of commands using the runners shell
      - name: Build and run tests
        run: ./gradlew build --no-daemon -PcpythonActivated=true

      # - name: Upload usvm test reports
      #   uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: usvm-tests-report-linux
      #     path: ./**/build/reports/tests/test/

      - name: Run Detekt
        run: ./gradlew detektMain detektTest --no-daemon

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif